kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-and-test
  image: golang:1.16
  commands:
  - go test ./...
  - go build -v .

- name: build-dist
  image: golang:1.16
  commands:
  - go get github.com/mitchellh/gox
  - | 
    gox -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}" \
        -osarch="linux/386 linux/amd64 linux/arm linux/arm64 windows/386 windows/adm64" \
        -ldflags="-X main.version=build-${DRONE_BUILD_NUMBER} -X main.revision=${DRONE_COMMIT_SHA}"

- name: docker
  image: plugins/docker
  settings:
    repo: makii42/untouched
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASSWORD
    dry_run: true
    experimental: true