---

kind: pipeline
type: docker
name: ci

platform:
  os: linux
  arch: amd64

steps:

- name: build-and-test
  image: golang:1.16
  commands:
  - go test ./...
  - go build -v .


- name: build-dist
  image: golang:1.16
  when:
    event:
    - push
    - pull_request
  commands:
  - go get github.com/mitchellh/gox
  - | 
    gox -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}" \
        -osarch="linux/386 linux/amd64 linux/arm linux/arm64 windows/386 windows/amd64" \
        -ldflags="-X main.version=build-${DRONE_BUILD_NUMBER} -X main.revision=${DRONE_COMMIT_SHA}"


- name: build-dist-release
  image: golang:1.16
  when:
    event:
    - tag
  commands:
  - go get github.com/mitchellh/gox
  - | 
    gox -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}" \
        -osarch="linux/386 linux/amd64 linux/arm linux/arm64 windows/386 windows/amd64" \
        -ldflags="-X main.version=${DRONE_TAG##v} -X main.revision=${DRONE_COMMIT_SHA}"


- name: upload-dist
  image: tsub/ghr
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  when:
    event:
    - tag
  commands:
  - ghr -owner ${DRONE_REPO_NAMESPACE} -replace ${DRONE_TAG} ./dist/

---

kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: golang:1.16
  commands:
  - go test ./...
  
- name: build
  image: golang:1.16
  commands:
  - sh build.sh
  environment:
    GOARCH: amd64
    GOOS: linux

- name: publish
  image: plugins/docker:18
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: Dockerfile.amd64
    repo: makii42/untouched
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASSWORD
  when:
    event:
    - push
    - tag

depends_on:
- ci

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: build
  image: golang:1.16
  commands:
  - sh build.sh
  environment:
    GOARCH: arm64
    GOOS: linux

- name: publish
  image: plugins/docker:18
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: Dockerfile.arm64v8
    repo: makii42/untouched
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASSWORD

trigger:
  event:
  - push
  - tag

depends_on:
- ci

---
kind: pipeline
type: docker
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
- name: build
  image: golang:1.16
  commands:
  - sh build.sh
  environment:
    GOARCH: arm
    GOOS: linux

# fails currentl :(
#- name: publish
#  image: plugins/docker:18
#  settings:
#    auto_tag: true
#    auto_tag_suffix: linux-arm
#    dockerfile: Dockerfile.arm32v7
#    repo: makii42/untouched
#    username:
#      from_secret: DOCKER_USER
#    password:
#      from_secret: DOCKER_PASSWORD

trigger:
  event:
  - push
  - tag

depends_on:
- ci

---
kind: pipeline
type: docker
name: manifest

steps:
- name: publish
  image: plugins/manifest:1.2
  settings:
    auto_tag: true
    ignore_missing: true
    spec: manifest.tmpl
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASSWORD

trigger:
  event:
  - push
  - tag

depends_on:
- linux-amd64
- linux-arm64
- linux-arm

