version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.2
    working_directory: /go/src/github.com/makii42/untouched
    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: go build .
      - run: |
          gox \
            -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}" \
            -osarch="linux/386 linux/amd64 linux/arm darwin/386 darwin/amd64 windows/386 windows/adm64" \
            -ldflags="-X main.version=$CIRCLE_TAG -X main.revision=$CIRCLE_SHA1"
      - run: cd dist && sha256sum untouched* | tee untouched-sha256sums.txt
      - run: cp Dockerfile ./dist
      - persist_to_workspace:
          root: ./dist
          paths:
            - "*"

  dist:
    docker:
      - image: tsub/ghr:latest
    working_directory: /go/src/github.com/makii42/untouched
    steps: 
      - attach_workspace:
          at: ./dist
      - run: ls -la ./dist/
      - run: cd dist && sha256sum -c untouched-sha256sums.txt 
      - run: ghr -username $CIRCLE_PROJECT_USERNAME -repository $CIRCLE_PROJECT_REPONAME --replace $CIRCLE_TAG dist/

  docker-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - attach_workspace:
          at: ./dist
      - setup_remote_docker
      - run: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
      - run: mv dist/Dockerfile .
      - run: docker build -t makii42/untouched:latest .
      - run: docker tag makii42/untouched:latest makii42/untouched:$CIRCLE_TAG
      - run: docker push makii42/untouched:latest
      - run: docker push makii42/untouched:$CIRCLE_TAG

workflows:
  version: 2
  build_and_dist:
    jobs: 
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - dist:
          requires:
            - build
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - docker-build:
          requires: 
            - dist
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/